### ISSUE TITLE
Asynchronous Cycles

### ISSUE THREAD

**Issue by zhululai** [layeredqueuing/V6#1]
The attached models contain cycles with asynchronous calls. They used to run smoothly with LQNS Win v6.0 BETA7, but LQNS Win v6.2 BETA1 now raises errors due to these cycles.

[async_tests.zip](https://github.com/layeredqueuing/V6/files/8717068/async_tests.zip)

**Comment by layeredqueuing** [comment]
Fixed, though so regressions have popped up which I will try to resolve shortly.  The attached SVG file shows the throughput results (with everything renamed).  
![bug-374-act](https://user-images.githubusercontent.com/11948604/171717620-c5eb9894-f66c-434d-9be7-e9b22e9ec097.svg)

**Comment by layeredqueuing** [comment]
Fixed with V5.26.

**Comment by zhululai** [comment]
> Fixed with V5.26.

I tried V5.26 downloaded from http://www.sce.carleton.ca/rads/lqns/LQNSdownload/. I still got an error message: Cycle in call graph. Do I miss anything?

**Comment by layeredqueuing** [comment]
You have to set 

#pragma cycles=t

(or run "lqns -Pcycles=t”)

to allow cycles in the call graph.  Calling yourself, directly or indirectly, with synchronous messaging may result in a deadlock on a real system.

**Comment by zhululai** [comment]
Thanks a lot. I obtained the same result for an optimization program as before.
