### ISSUE TITLE
Activity previously used in a fork.

### ISSUE THREAD

**Issue by gcasale** [layeredqueuing/V6#2]
The attached model has been generated to analyze a standard closed queueing network using a LQN. 

LQNS reports:
"error: Activity "A1_2" previously used in a fork."
However, the model has no forks.

[tp54aae36a.zip](https://github.com/layeredqueuing/V6/files/8949816/tp54aae36a.zip)

**Comment by gcasale** [comment]
If it helps spotting the bug, we subsequently found that adding two extra dummy activities after CS_1_3_1 and CS_1_4_1 and then or-join them to A1_2 fixes the issue, though the overall bug is still probably there. New model attached.

We also tried before to change the post-OR with probability "1" into post but that did not help.

[tp54aae36a_new.zip](https://github.com/layeredqueuing/V6/files/8950139/tp54aae36a_new.zip)

**Comment by layeredqueuing** [comment]
There are a couple of errors in the construction of the model.  Activity A1_2 needs to be duplicated as it is appearing twice as an edge in the graph (think of activities as edges and the pre-post stuff as nodes, the edges are named, the nodes are not).  Also, the server entries, defined by activities, need to reply.  The drawing program will accept a <pre> (join) with more than one activity, though I don't think it is constructed internally correctly.  This is a bug.

**Comment by layeredqueuing** [comment]
The error handling has been improved and now reports:
lqns tp54aae36a.lqnx
tp54aae36a.lqnx:73: error: Task "RefTask:1", activity "A1_2" previously used in the fork at line 62.

(pre's are joins and post's are forks in the <precedence> elements).  
The improved error messaging will appear in the next push to the repo and in V.57, V6.2.27 eventually).

**Comment by layeredqueuing** [comment]
Hi Giuliano,

There are a couple of errors in the construction of the model.  I have attached a diff of the changes, plus an image file.  A1_2 needs to be duplicated as it is appearing twice as an edge in the graph.  (think of activities as edges and the pre-post stuff as nodes, the edges are named, the nodes are not).  Also, the server entries, defined by activities, need to reply.  The drawing program will accept a <pre> with more than one activity, though I don’t think it is constructed internally correctly.  This is a bug.


Gregory Franks, Ph.D. P.Eng
Associate Chair - Undergraduate Studies
Department of Systems and Computer Engineering
Carleton University
