### ISSUE TITLE
QNAP2 file

### ISSUE THREAD

**Issue by gcasale** [layeredqueuing/V6#4]
Hi,

I am trying to compile V6: it is not working at the moment because "qnap2_scan.c" is missing, can this be added?

As a side note, README-LOCAL asks to run "./.configure-ubuntu" but this is now .configure-llvm-ubuntu

I also had to launch "sudo apt install clang lldb lld" to get the compilation to start.

Thanks
Giuliano

**Comment by layeredqueuing** [comment]
qnap2_scan is a derived file.  I've updated the Makefile.am file to build it first.  The build system is more robust now.  Start with autogen.sh if building from the src repo.  You don't need to use clang.  Also, for ubuntu, the simulator will work if built using -m32.  There is a .configure file for that now.
